menu:
  Home: /archives
  About: /about.html

googleTrackId: G-8MHZNDKC11

giscus: true
data_repo: SYYANI/SYYANI.github.io
data_repo_id: R_kgDOI1kV-A
data_category: Announcements
data_category_id: DIC_kwDOI1kV-M4CTyh9
data_mapping: og:title
data_strict: 1
data_reactions_enabled: 1
data_emit_metadata: 0
data_input_position: top
data_theme: preferred_color_scheme
data_lang: zh-CN
data_loading:
