menu:
  Home: /
  Archives: /archives
  About: /about.html

googleTrackId: G-TNEF16TMV4

giscus: true
data_repo: syyani/syyani.github.io
data_repo_id: R_kgDOH8N7xQ
data_category: Announcements
data_category_id: DIC_kwDOH8N7xc4CRQCg
data_mapping: og:title
data_strict: 1
data_reactions_enabled: 1
data_emit_metadata: 0
data_input_position: top
data_theme: preferred_color_scheme
data_lang: zh-CN
data_loading:
