const fs = require('fs');
const moment = require('moment');
const path = require('path');

const DEFAULT_DIGEST_ROOT = path.resolve(__dirname, '..', '..', 'digest', 'content', 'digest');
const DIGEST_ROOT = path.resolve(process.env.DIGEST_CONTENT_DIR || DEFAULT_DIGEST_ROOT);

function walkFiles(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkFiles(fullPath));
      continue;
    }
    files.push(fullPath);
  }

  return files.sort((left, right) => {
    const leftBase = path.basename(left).toLowerCase();
    const rightBase = path.basename(right).toLowerCase();
    const leftIsCopy = /\bcopy\b/.test(leftBase);
    const rightIsCopy = /\bcopy\b/.test(rightBase);

    if (leftIsCopy !== rightIsCopy) {
      return leftIsCopy ? 1 : -1;
    }

    return left.localeCompare(right);
  });
}

function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function stripMarkdown(text) {
  return text
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/^>\s?/gm, '')
    .replace(/[#*_~>-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function buildSummary(body, title, explicitSummary) {
  if (explicitSummary) return explicitSummary;

  const paragraphs = body
    .split(/\n\s*\n/)
    .map((block) => block.trim())
    .filter(Boolean)
    .map((block) => block.replace(/^#+\s*/, '').trim())
    .filter((block) => {
      if (!block) return false;
      if (title && block === title) return false;
      if (/^(notes|note)$/i.test(block)) return false;
      if (/^\d{4}(?:[-/]|\s*年\s*)\d{1,2}(?:[-/]|\s*月\s*)\d{1,2}\s*日?(?:\s+\d{1,2}:\d{2})?$/u.test(block)) return false;
      if (/^\*\*Authors?\*\*:/i.test(block)) return false;
      if (/^\*Generated by .*\*$/i.test(block)) return false;
      return true;
    });

  const firstParagraph = paragraphs.length > 0 ? stripMarkdown(paragraphs[0]) : stripMarkdown(body);
  return firstParagraph.slice(0, 180);
}

function escapeRegExp(text) {
  return String(text).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function normalizeBody(body, title) {
  if (!title) return body;

  const titlePattern = new RegExp(`^\\s*#\\s+${escapeRegExp(title)}\\s*\\n+`, 'u');
  return body.replace(titlePattern, '');
}

function parseTomlValue(rawValue) {
  const value = rawValue.trim();

  if (value.startsWith('[') && value.endsWith(']')) {
    const inner = value.slice(1, -1).trim();
    if (!inner) return [];
    return inner
      .split(',')
      .map((item) => item.trim())
      .map((item) => parseTomlValue(item));
  }

  if (
    (value.startsWith("'") && value.endsWith("'")) ||
    (value.startsWith('"') && value.endsWith('"'))
  ) {
    return value.slice(1, -1);
  }

  if (value === 'true') return true;
  if (value === 'false') return false;

  const numericValue = Number(value);
  if (!Number.isNaN(numericValue)) return numericValue;

  return value;
}

function parseDigestFile(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const match = raw.match(/^\+\+\+\s*\n([\s\S]*?)\n\+\+\+\s*\n?([\s\S]*)$/);
  const frontMatter = {};
  let body = raw;

  if (match) {
    body = match[2];
    const frontMatterLines = match[1].split('\n');
    for (const line of frontMatterLines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;

      const separatorIndex = trimmed.indexOf('=');
      if (separatorIndex === -1) continue;

      const key = trimmed.slice(0, separatorIndex).trim();
      const value = trimmed.slice(separatorIndex + 1).trim();
      frontMatter[key] = parseTomlValue(value);
    }
  }

  return { frontMatter, body };
}

function toRoutePath(relativePath, slug) {
  const normalized = relativePath.split(path.sep).join('/');
  if (normalized.endsWith('/index.md')) {
    return `digest/${normalized.slice(0, -'index.md'.length)}index.html`;
  }

  if (normalized.endsWith('.md')) {
    if (slug) {
      return `digest/${slug}/index.html`;
    }
    return `digest/${normalized.slice(0, -3)}/index.html`;
  }

  return `digest/${normalized}`;
}

function formatDateLabel(date) {
  if (!date || typeof date.format !== 'function') return '';
  return date.format('YYYY-MM-DD');
}

hexo.extend.generator.register('digest-pages', function digestPages(locals) {
  if (!fs.existsSync(DIGEST_ROOT)) {
    hexo.log.warn(`[digest] content directory not found: ${DIGEST_ROOT}`);
    return [];
  }

  hexo.log.info(`[digest] loading content from ${DIGEST_ROOT}`);

  const files = walkFiles(DIGEST_ROOT);
  const pages = [];
  const items = [];
  const seenRoutePaths = new Set();

  for (const filePath of files) {
    const basename = path.basename(filePath);
    if (basename.startsWith('.')) continue;

    if (!filePath.endsWith('.md')) {
      const relativePath = path.relative(DIGEST_ROOT, filePath);
      const routePath = toRoutePath(relativePath);
      pages.push({
        path: routePath,
        data: () => fs.createReadStream(filePath),
      });
      continue;
    }

    const { frontMatter, body } = parseDigestFile(filePath);
    if (frontMatter.draft) continue;

    const relativePath = path.relative(DIGEST_ROOT, filePath);
    const routePath = toRoutePath(relativePath, frontMatter.slug);
    if (seenRoutePaths.has(routePath)) {
      hexo.log.warn(`[digest] duplicate route skipped: ${routePath} from ${filePath}`);
      continue;
    }
    seenRoutePaths.add(routePath);

    const stats = fs.statSync(filePath);
    const parsedDate = moment(frontMatter.date || stats.mtime);
    const pageTitle = frontMatter.title || path.basename(filePath, '.md');
    const normalizedBody = normalizeBody(body, pageTitle);
    const summary = buildSummary(normalizedBody, pageTitle, frontMatter.summary);
    const renderedBody = hexo.render.renderSync({
      path: filePath,
      text: normalizedBody,
    });

    items.push({
      date: parsedDate,
      routePath: `/${routePath.replace(/index\.html$/, '')}`,
      title: pageTitle,
      summary,
      tags: Array.isArray(frontMatter.tags) ? frontMatter.tags : [],
    });

    const pageData = {
      title: pageTitle,
      path: routePath,
      date: parsedDate,
      updated: parsedDate,
      content: renderedBody,
      excerpt: summary,
      description: summary,
      comments: false,
      tags: [],
      categories: [],
    };

    pages.push({
      path: routePath,
      layout: ['post', 'page', 'index'],
      data: {
        page: pageData,
        title: pageTitle,
        path: routePath,
        date: parsedDate,
        description: summary,
        content: renderedBody,
      },
    });
  }

  items.sort((left, right) => right.date - left.date);

  const listHtml = [
    '<div class="digest-module">',
    items.length === 0 ? '<p>还没有可展示的 digest。</p>' : '',
    ...items.map((item) => {
      const tagsHtml =
        item.tags.length > 0
          ? `<p><strong>标签：</strong>${item.tags.map(escapeHtml).join(' / ')}</p>`
          : '';

      return [
        '<article class="digest-card">',
        `  <h2><a href="${item.routePath}">${escapeHtml(item.title)}</a></h2>`,
        item.date ? `  <p><strong>日期：</strong>${escapeHtml(formatDateLabel(item.date))}</p>` : '',
        tagsHtml,
        `  <p>${escapeHtml(item.summary)}</p>`,
        `  <p><a href="${item.routePath}">阅读全文</a></p>`,
        '</article>',
      ]
        .filter(Boolean)
        .join('\n');
    }),
    '</div>',
  ]
    .filter(Boolean)
    .join('\n');

  const digestIndexDate = items[0] ? items[0].date : moment();
  const digestIndexPage = {
    title: 'Digest',
    path: 'digest/index.html',
    date: digestIndexDate,
    updated: digestIndexDate,
    content: listHtml,
    comments: false,
    tags: [],
    categories: [],
  };

  pages.push({
    path: 'digest/index.html',
    layout: ['page', 'post', 'index'],
    data: {
      page: digestIndexPage,
      title: 'Digest',
      path: 'digest/index.html',
      date: digestIndexDate,
      description: '这里汇总展示 digest 内容仓库中维护的摘要内容。',
      content: listHtml,
      digestItems: items,
    },
  });

  return pages;
});
